

brew "antidote" # zsh plugin manager
brew "caddy"
brew "ccat"
brew "cloudflared"
brew "fzf"
brew "rust"
brew "jq"
brew "nvm"
brew "go"
brew "rg"
brew "screenfetch"
brew "tree"
brew "volta"
brew "nvim"
brew "marksman"
brew "zk"
brew "stylua"
brew "python"
brew "pipx"
brew "flyctl"

cask "ghostty"
cask "cleanshot"
cask "1password"
cask "raycast"
cask "discord"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "karabiner-elements"
cask "keybase"
cask "loom"
cask "ngrok"
cask "notion"
cask "postman"
cask "readdle-spark"
cask "slack"
cask "screenflow"
cask "spotify"
cask "vanilla" # hide mac menu bar
cask "mongodb-compass"
cask "obsidian"
cask "cursor"
cask "warp"
cask "lm-studio"
cask "screen-studio"
cask "iterm2"
cask "kitty"
cask "tmux"
cask "tmuxp"

tap "supabase/tap"
brew "supabase"

cask "chatgpt"
cask "claude"
cask "claude-code"
